[2024-02-19T04:58:16.774+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Load_user_dim_table manual__2024-02-19T04:56:30.950941+00:00 [queued]>
[2024-02-19T04:58:16.779+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Load_user_dim_table manual__2024-02-19T04:56:30.950941+00:00 [queued]>
[2024-02-19T04:58:16.780+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-02-19T04:58:16.787+0000] {taskinstance.py:2192} INFO - Executing <Task(LoadDimensionOperator): Load_user_dim_table> on 2024-02-19 04:56:30.950941+00:00
[2024-02-19T04:58:16.791+0000] {standard_task_runner.py:60} INFO - Started process 29427 to run task
[2024-02-19T04:58:16.795+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Load_user_dim_table', 'manual__2024-02-19T04:56:30.950941+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpj8qc8cet']
[2024-02-19T04:58:16.799+0000] {standard_task_runner.py:88} INFO - Job 141: Subtask Load_user_dim_table
[2024-02-19T04:58:16.829+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Load_user_dim_table manual__2024-02-19T04:56:30.950941+00:00 [running]> on host 6b28116ad14a
[2024-02-19T04:58:16.882+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-19T04:56:30.950941+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-19T04:56:30.950941+00:00'
[2024-02-19T04:58:16.889+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-19T04:58:16.890+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-19T04:58:16.898+0000] {load_dimension.py:36} INFO - dim.dim_users is being inserted
[2024-02-19T04:58:16.902+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:58:22.799+0000] {sql.py:432} INFO - Running statement: delete from dim.dim_users, parameters: None
[2024-02-19T04:58:24.205+0000] {sql.py:441} INFO - Rows affected: 104
[2024-02-19T04:58:26.320+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:58:31.190+0000] {sql.py:432} INFO - Running statement: 
    insert into dim.dim_users (userid, firstname, lastname, gender, level)
        SELECT distinct userid, firstname, lastname, gender, level
        FROM staging.staging_events
        WHERE page='NextSong'
    , parameters: None
[2024-02-19T04:58:36.340+0000] {sql.py:441} INFO - Rows affected: 104
[2024-02-19T04:58:37.997+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=final_project, task_id=Load_user_dim_table, execution_date=20240219T045630, start_date=20240219T045816, end_date=20240219T045837
[2024-02-19T04:58:38.047+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-19T04:58:38.074+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
