[2024-02-18T06:03:29.450+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Stage_events manual__2024-02-18T06:03:27.456453+00:00 [queued]>
[2024-02-18T06:03:29.454+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Stage_events manual__2024-02-18T06:03:27.456453+00:00 [queued]>
[2024-02-18T06:03:29.454+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-18T06:03:29.460+0000] {taskinstance.py:2192} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2024-02-18 06:03:27.456453+00:00
[2024-02-18T06:03:29.463+0000] {standard_task_runner.py:60} INFO - Started process 20508 to run task
[2024-02-18T06:03:29.466+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Stage_events', 'manual__2024-02-18T06:03:27.456453+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmp490i8xzr']
[2024-02-18T06:03:29.469+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask Stage_events
[2024-02-18T06:03:29.500+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Stage_events manual__2024-02-18T06:03:27.456453+00:00 [running]> on host 6b28116ad14a
[2024-02-18T06:03:29.558+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Stage_events' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T06:03:27.456453+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T06:03:27.456453+00:00'
[2024-02-18T06:03:29.565+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-18T06:03:29.566+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-18T06:03:29.578+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-18T06:03:34.167+0000] {sql.py:432} INFO - Running statement: create schema if not exists staging, parameters: None
[2024-02-18T06:03:57.218+0000] {stage_redshift.py:52} INFO - Drop table staging.staging_events from destination Redshift table
[2024-02-18T06:03:57.223+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-18T06:04:02.649+0000] {sql.py:432} INFO - Running statement: Drop table if exists staging.staging_events, parameters: None
[2024-02-18T06:04:04.229+0000] {stage_redshift.py:55} INFO - Create table staging.staging_events from destination Redshift table
[2024-02-18T06:04:04.257+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-18T06:04:08.675+0000] {sql.py:432} INFO - Running statement: 
    create table if not exists staging.staging_events (
        artist text,
        auth text,
        firstname text,
        gender text,
        iteminsession int,
        lastname text,
        length double precision,
        level text,
        location text,
        method text,
        page text,
        registration bigint,
        sessionid int,
        song text,
        status int,
        ts bigint,
        useragent varchar(1000),
        userid text
    )
    , parameters: None
[2024-02-18T06:04:10.803+0000] {stage_redshift.py:58} INFO - Copying data from S3 to Redshift
[2024-02-18T06:04:10.804+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.805+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.805+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.806+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.806+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.807+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.807+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.808+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.808+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.809+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.809+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.809+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-02-18T06:04:10.810+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/plugins/custom_operators/stage_redshift.py", line 64, in execute
    self.s3_path,
AttributeError: 'StageToRedshiftOperator' object has no attribute 's3_path'
[2024-02-18T06:04:10.818+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=final_project, task_id=Stage_events, execution_date=20240218T060327, start_date=20240218T060329, end_date=20240218T060410
[2024-02-18T06:04:10.828+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task Stage_events ('StageToRedshiftOperator' object has no attribute 's3_path'; 20508)
[2024-02-18T06:04:10.838+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-18T06:04:10.849+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
