[2024-02-19T04:58:39.079+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Run_data_quality_checks manual__2024-02-19T04:56:30.950941+00:00 [queued]>
[2024-02-19T04:58:39.084+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Run_data_quality_checks manual__2024-02-19T04:56:30.950941+00:00 [queued]>
[2024-02-19T04:58:39.084+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-02-19T04:58:39.090+0000] {taskinstance.py:2192} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2024-02-19 04:56:30.950941+00:00
[2024-02-19T04:58:39.094+0000] {standard_task_runner.py:60} INFO - Started process 29433 to run task
[2024-02-19T04:58:39.097+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Run_data_quality_checks', 'manual__2024-02-19T04:56:30.950941+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpfpweeljx']
[2024-02-19T04:58:39.100+0000] {standard_task_runner.py:88} INFO - Job 144: Subtask Run_data_quality_checks
[2024-02-19T04:58:39.127+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Run_data_quality_checks manual__2024-02-19T04:56:30.950941+00:00 [running]> on host 6b28116ad14a
[2024-02-19T04:58:39.164+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2024-02-19T04:56:30.950941+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-19T04:56:30.950941+00:00'
[2024-02-19T04:58:39.169+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-19T04:58:39.170+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-19T04:58:39.179+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:58:45.132+0000] {sql.py:432} INFO - Running statement: select count(*) from staging.staging_events, parameters: None
[2024-02-19T04:58:46.538+0000] {sql.py:441} INFO - Rows affected: 1
[2024-02-19T04:58:47.230+0000] {data_quality.py:36} INFO - Data quality on table staging.staging_events check passed with 8056 records
[2024-02-19T04:58:47.239+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:58:54.486+0000] {sql.py:432} INFO - Running statement: select count(*) from staging.staging_songs, parameters: None
[2024-02-19T04:59:02.921+0000] {sql.py:441} INFO - Rows affected: 1
[2024-02-19T04:59:03.830+0000] {data_quality.py:36} INFO - Data quality on table staging.staging_songs check passed with 14896 records
[2024-02-19T04:59:03.843+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:59:08.596+0000] {sql.py:432} INFO - Running statement: select count(*) from fact.fact_song_plays, parameters: None
[2024-02-19T04:59:10.182+0000] {sql.py:441} INFO - Rows affected: 1
[2024-02-19T04:59:11.220+0000] {data_quality.py:36} INFO - Data quality on table fact.fact_song_plays check passed with 6820 records
[2024-02-19T04:59:11.245+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:59:16.200+0000] {sql.py:432} INFO - Running statement: select count(*) from dim.dim_users, parameters: None
[2024-02-19T04:59:17.542+0000] {sql.py:441} INFO - Rows affected: 1
[2024-02-19T04:59:18.069+0000] {data_quality.py:36} INFO - Data quality on table dim.dim_users check passed with 104 records
[2024-02-19T04:59:18.080+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:59:22.393+0000] {sql.py:432} INFO - Running statement: select count(*) from dim.dim_songs, parameters: None
[2024-02-19T04:59:23.687+0000] {sql.py:441} INFO - Rows affected: 1
[2024-02-19T04:59:24.258+0000] {data_quality.py:36} INFO - Data quality on table dim.dim_songs check passed with 14896 records
[2024-02-19T04:59:24.262+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:59:30.201+0000] {sql.py:432} INFO - Running statement: select count(*) from dim.dim_artists, parameters: None
[2024-02-19T04:59:31.774+0000] {sql.py:441} INFO - Rows affected: 1
[2024-02-19T04:59:32.414+0000] {data_quality.py:36} INFO - Data quality on table dim.dim_artists check passed with 10025 records
[2024-02-19T04:59:32.429+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T04:59:37.262+0000] {sql.py:432} INFO - Running statement: select count(*) from dim.dim_time, parameters: None
[2024-02-19T04:59:39.529+0000] {sql.py:441} INFO - Rows affected: 1
[2024-02-19T04:59:40.080+0000] {data_quality.py:36} INFO - Data quality on table dim.dim_time check passed with 6820 records
[2024-02-19T04:59:40.087+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=final_project, task_id=Run_data_quality_checks, execution_date=20240219T045630, start_date=20240219T045839, end_date=20240219T045940
[2024-02-19T04:59:40.132+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-19T04:59:40.145+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
