[2024-02-18T09:38:17.167+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Load_time_dim_table manual__2024-02-18T09:35:04.108286+00:00 [queued]>
[2024-02-18T09:38:17.173+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Load_time_dim_table manual__2024-02-18T09:35:04.108286+00:00 [queued]>
[2024-02-18T09:38:17.173+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-18T09:38:17.182+0000] {taskinstance.py:2192} INFO - Executing <Task(LoadDimensionOperator): Load_time_dim_table> on 2024-02-18 09:35:04.108286+00:00
[2024-02-18T09:38:17.187+0000] {standard_task_runner.py:60} INFO - Started process 24015 to run task
[2024-02-18T09:38:17.191+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Load_time_dim_table', 'manual__2024-02-18T09:35:04.108286+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpnk9trh4t']
[2024-02-18T09:38:17.195+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask Load_time_dim_table
[2024-02-18T09:38:17.231+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Load_time_dim_table manual__2024-02-18T09:35:04.108286+00:00 [running]> on host 6b28116ad14a
[2024-02-18T09:38:17.289+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T09:35:04.108286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T09:35:04.108286+00:00'
[2024-02-18T09:38:17.299+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-18T09:38:17.300+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-18T09:38:17.308+0000] {load_dimension.py:34} INFO - dim.dim_time is being inserted
[2024-02-18T09:38:17.314+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-18T09:38:22.153+0000] {sql.py:432} INFO - Running statement: drop table if exists dim.dim_time, parameters: None
[2024-02-18T09:38:25.349+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-18T09:38:30.864+0000] {sql.py:432} INFO - Running statement: 
        SELECT start_time, 
            extract(hour from start_time) as hour, 
            extract(day from start_time) as day, 
            extract(week from start_time) as week, 
            extract(month from start_time) as month, 
            extract(year from start_time) as year, 
            extract(dayofweek from start_time) as weekday
        into dim.dim_time
        FROM fact.fact_song_plays
    , parameters: None
[2024-02-18T09:38:35.277+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=final_project, task_id=Load_time_dim_table, execution_date=20240218T093504, start_date=20240218T093817, end_date=20240218T093835
[2024-02-18T09:38:35.329+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-18T09:38:35.355+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
